Pusing the converted python3 files that cause the following error.
  File "/home/ali/Documents/MPRAsnakeflow/workflow/rules/../scripts/count/FastQ2doubleIndexBAM_python3.py", line 281, in <module>
    outfiles[None][0].write(forward)
  File "pysam/libcalignmentfile.pyx", line 1710, in pysam.libcalignmentfile.AlignmentFile.write
  File "pysam/libcalignmentfile.pyx", line 1742, in pysam.libcalignmentfile.AlignmentFile.write
OSError: sam_write1 failed with error code -1
[E::bgzf_close] File write failed